"""fix status

Revision ID: 737ab3912d7c
Revises: 6de9cfeee43c
Create Date: 2025-12-09 19:52:44.441003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '737ab3912d7c'
down_revision: Union[str, Sequence[str], None] = '6de9cfeee43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN operations
    # This change is not applicable to SQLite databases
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN operations
    # This change is not applicable to SQLite databases
    pass
    # ### end Alembic commands ###
