"""rename rewiews to reviews and fix model

Revision ID: 8f05e8739a86
Revises: a1b2c3d4e5f
Create Date: 2025-12-18 14:34:33.716192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f05e8739a86'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Table is already renamed in previous migration
    # Just ensure it has the correct schema
    # Since we're working with SQLite, we'll skip explicit table creation
    # which would conflict with existing table
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Since we didn't create the table in upgrade, we don't need to drop it here
    pass
    # ### end Alembic commands ###
