"""rename rewiews to reviews

Revision ID: a1b2c3d4e5f
Revises: 9d4e1a2b3c5a
Create Date: 2025-12-18 11:15:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f'
down_revision = '9d4e1a2b3c5a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the old table exists before renaming
    connection = op.get_bind()
    result = connection.execute(text("SELECT name FROM sqlite_master WHERE type='table' AND name='rewiews';"))
    if result.fetchone():
        op.rename_table('rewiews', 'reviews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if the new table exists before renaming back
    connection = op.get_bind()
    result = connection.execute(text("SELECT name FROM sqlite_master WHERE type='table' AND name='reviews';"))
    if result.fetchone():
        op.rename_table('reviews', 'rewiews')
    # ### end Alembic commands ###